name: ecommerce_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  fade_shimmer: ^2.3.0
  flutter:
    sdk: flutter
  flutter_animator: ^3.2.2
  flutter_bloc: ^9.0.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  font_awesome_flutter: ^10.8.0
  freezed_annotation: ^2.4.4
  get_it: ^7.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.9.0
  logger: ^2.5.0
  path_provider: ^2.1.5

dev_dependencies:
  analyzer:
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.8
  json_serializable: ^6.9.3

flutter_intl:
  enabled: true
  arb_dir: lib/src/core/config/l10n
  output_dir: lib/src/core/config/l10n/generated

flutter:
  uses-material-design: true
